### ISSUE TITLE
wrong prediction matrix in time raster imputation

### ISSUE THREAD

**Issue by dmongin** [stefvanbuuren/fimdbook#5]
The code https://github.com/stefvanbuuren/fimdbook/blob/master/R/fimd.R#L3028 is inconsistnet with the legend below (https://github.com/stefvanbuuren/fimdbook/blob/master/Rmd/11-longitudinal.Rmd#L834), which says:

```r
pred[Y, paste(x, 1:9, sep = )] <- 2
```

whereas the code indicates  

```r
pred[Y, paste("x", 2:9, sep = "")] <- 1
```

More generally, there are no random effect in the example code (all predictors are set to 1 appart from the class variable), when the reader expect random effects. I guesss this is a typo, and should be corrected ?

**Comment by stefvanbuuren** [comment]
Thanks for your note. This concerns page 329 in FIMD 2. 

This is indeed a typo. The correct code should be

```r
## ----tbcimppred----------------------------------------------------------
pred <- make.predictorMatrix(data2)
pred[1:nrow(pred), 1:ncol(pred)] <- 0
pred[Y, "id"] <- (-2)
pred[Y, "sex"] <- 1
pred[Y, paste("x", 2:9, sep = "")] <- 2
pred[Y[1], Y[2]] <- 2
pred[Y[2], Y[1]] <- 2
pred[Y[3], Y[1:2]] <- 2
```

so that we have nine random effects for age (1 intercept and 8 slope parameters), and three random effects for the incomplete variables (`hgt.z`, `wgt.z` and `hdc.z`). 

I suspect that Figure 11.7 was created with the correct script. This figure is identical to Figure 9.6 of the first edition, which uses the correct code, as given above.

There is now an alternative way to calculate this plot. See Figure 20 in <https://stefvanbuuren.name/publications/2021_brokenstick_JSS_manuscript.pdf> for more details.
